# permissions for end users to view edabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edabackup-viewer-role
rules:
- apiGroups:
  - eda.ansible.com
  resources:
  - edabackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eda.ansible.com
  resources:
  - edabackups/status
  verbs:
  - get
