# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/eda.ansible.com_edas.yaml
- bases/eda.ansible.com_edabackups.yaml
- bases/eda.ansible.com_edarestores.yaml
#+kubebuilder:scaffold:crdkustomizeresource
