---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf


dependencies:

  python_interpreter:
    python_path: "/usr/bin/python3"
    package_system: "python3"

  system:
    - gcc
    - python3-ethtool
    - python3-dmidecode

  python:
    - libnl
    - adal==1.2.2
    - ansible==2.9.27
    - ansible-tower-cli==3.3.9
    - apache-libcloud==2.5.0
    - appdirs==1.4.3
    - applicationinsights==0.11.9
    - argcomplete==1.10.3
    - azure-cli-core==2.0.35
    - azure-cli-nspkg==3.0.2
    - azure-common==1.1.11
    - azure-graphrbac==0.40.0
    - azure-keyvault==1.0.0a1
    - azure-mgmt-authorization==0.51.1
    - azure-mgmt-automation==0.1.1
    - azure-mgmt-batch==5.0.1
    - azure-mgmt-cdn==3.0.0
    - azure-mgmt-compute==4.4.0
    - azure-mgmt-containerinstance==1.4.0
    - azure-mgmt-containerregistry==2.0.0
    - azure-mgmt-containerservice==4.4.0
    - azure-mgmt-cosmosdb==0.5.2
    - azure-mgmt-devtestlabs==3.0.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-hdinsight==0.1.0
    - azure-mgmt-iothub==0.7.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==0.2.0
    - azure-mgmt-marketplaceordering==0.1.0
    - azure-mgmt-monitor==0.5.2
    - azure-mgmt-network==2.3.0
    - azure-mgmt-nspkg==2.0.0
    - azure-mgmt-rdbms==1.4.1
    - azure-mgmt-redis==5.0.0
    - azure-mgmt-resource==2.1.0
    - azure-mgmt-servicebus==0.5.3
    - azure-mgmt-sql==0.10.0
    - azure-mgmt-storage==3.1.0
    - azure-mgmt-trafficmanager==0.50.0
    - azure-mgmt-web==0.41.0
    - azure-nspkg==2.0.0
    - azure-storage==0.35.1

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
