---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python_interpreter:
    python_path: "/usr/bin/python3"
    package_system: "python3"

  galaxy:
    collections:
      - awx.awx
      - infra.controller_configuration

  system:
    - gcc
    - python39-devel
    - openldap-devel

  python:
    - python-ldap==3.4.4
    - XlsxWriter==3.2.0

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
