---
controller_settings:
  - settings:
      ACTIVITY_STREAM_ENABLED: "true"
      ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: "false"
      ORG_ADMINS_CAN_SEE_ALL_USERS: "true"
      MANAGE_ORGANIZATION_AUTH: "true"
      TOWER_URL_BASE: "https://towerhost"
      REMOTE_HOST_HEADERS:
        - REMOTE_ADDR
        - REMOTE_HOST
      PROXY_IP_ALLOWED_LIST:
        []
      CSRF_TRUSTED_ORIGINS:
        []
      LICENSE:
        {}
      REDHAT_USERNAME: ""
      REDHAT_PASSWORD: ""
      SUBSCRIPTIONS_USERNAME: ""
      SUBSCRIPTIONS_PASSWORD: ""
      AUTOMATION_ANALYTICS_URL: "https://example.com"
      INSTALL_UUID: "8ea49f6b-9499-4f55-bc6f-c5282209048a"
      DEFAULT_CONTROL_PLANE_QUEUE_NAME: "controlplane"
      DEFAULT_EXECUTION_QUEUE_NAME: "default"
      CUSTOM_VENV_PATHS:
        []
      AD_HOC_COMMANDS:
        - command
        - shell
        - yum
        - apt
        - apt_key
        - apt_repository
        - apt_rpm
        - service
        - group
        - user
        - mount
        - ping
        - selinux
        - setup
        - win_ping
        - win_service
        - win_updates
        - win_group
        - win_user
      ALLOW_JINJA_IN_EXTRA_VARS: "template"
      AWX_ISOLATION_BASE_PATH: "/tmp"
      AWX_ISOLATION_SHOW_PATHS:
        - /etc/pki/ca-trust:/etc/pki/ca-trust:O
        - /usr/share/pki:/usr/share/pki:O
      AWX_TASK_ENV:
        GIT_SSL_NO_VERIFY: 'true'
      AWX_RUNNER_KEEPALIVE_SECONDS: "0"
      GALAXY_TASK_ENV:
        GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
        ANSIBLE_FORCE_COLOR: 'false'
      INSIGHTS_TRACKING_STATE: "false"
      PROJECT_UPDATE_VVV: "false"
      AWX_ROLES_ENABLED: "true"
      AWX_COLLECTIONS_ENABLED: "true"
      AWX_SHOW_PLAYBOOK_LINKS: "false"
      AWX_MOUNT_ISOLATED_PATHS_ON_K8S: "false"
      GALAXY_IGNORE_CERTS: "false"
      STDOUT_MAX_BYTES_DISPLAY: "1048576"
      EVENT_STDOUT_MAX_BYTES_DISPLAY: "1024"
      MAX_WEBSOCKET_EVENT_RATE: "30"
      SCHEDULE_MAX_JOBS: "10"
      AWX_ANSIBLE_CALLBACK_PLUGINS:
        []
      DEFAULT_JOB_TIMEOUT: "0"
      DEFAULT_JOB_IDLE_TIMEOUT: "0"
      DEFAULT_INVENTORY_UPDATE_TIMEOUT: "0"
      DEFAULT_PROJECT_UPDATE_TIMEOUT: "0"
      ANSIBLE_FACT_CACHE_TIMEOUT: "0"
      MAX_FORKS: "200"
      LOG_AGGREGATOR_USERNAME: ""
      LOG_AGGREGATOR_PASSWORD: ""
      LOG_AGGREGATOR_LOGGERS:
        - awx
        - activity_stream
        - job_events
        - system_tracking
        - broadcast_websocket
      LOG_AGGREGATOR_INDIVIDUAL_FACTS: "false"
      LOG_AGGREGATOR_ENABLED: "false"
      LOG_AGGREGATOR_TOWER_UUID: ""
      LOG_AGGREGATOR_PROTOCOL: "https"
      LOG_AGGREGATOR_TCP_TIMEOUT: "5"
      LOG_AGGREGATOR_VERIFY_CERT: "true"
      LOG_AGGREGATOR_LEVEL: "INFO"
      LOG_AGGREGATOR_ACTION_QUEUE_SIZE: "131072"
      LOG_AGGREGATOR_ACTION_MAX_DISK_USAGE_GB: "1"
      LOG_AGGREGATOR_MAX_DISK_USAGE_PATH: "/var/lib/awx"
      LOG_AGGREGATOR_RSYSLOGD_DEBUG: "false"
      API_400_ERROR_LOG_FORMAT: "status {status_code} received by user {user_name} attempting to access {url_path} from {remote_addr}"
      AUTOMATION_ANALYTICS_LAST_ENTRIES: ""
      AUTOMATION_ANALYTICS_GATHER_INTERVAL: "14400"
      IS_K8S: "true"
      BULK_JOB_MAX_LAUNCH: "100"
      BULK_HOST_MAX_CREATE: "100"
      BULK_HOST_MAX_DELETE: "250"
      UI_NEXT: "true"
      SUBSCRIPTION_USAGE_MODEL: ""
      CLEANUP_HOST_METRICS_LAST_TS: "2025-10-28T16:16:58.324979Z"
      HOST_METRIC_SUMMARY_TASK_LAST_TS: "2025-10-28T16:47:00.352019Z"
      AWX_CLEANUP_PATHS: "true"
      AWX_REQUEST_PROFILE: "false"
      DEFAULT_CONTAINER_RUN_OPTIONS:
        - --network
        - slirp4netns:enable_ipv6=true
      RECEPTOR_RELEASE_WORK: "true"
      SESSION_COOKIE_AGE: "1800"
      SESSIONS_PER_USER: "-1"
      DISABLE_LOCAL_AUTH: "false"
      AUTH_BASIC_ENABLED: "true"
      OAUTH2_PROVIDER:
        ACCESS_TOKEN_EXPIRE_SECONDS: 31536000000
        AUTHORIZATION_CODE_EXPIRE_SECONDS: 600
        REFRESH_TOKEN_EXPIRE_SECONDS: 2628000
      ALLOW_OAUTH2_FOR_EXTERNAL_USERS: "false"
      LOGIN_REDIRECT_OVERRIDE: ""
      ALLOW_METRICS_FOR_ANONYMOUS_USERS: "false"
      PENDO_TRACKING_STATE: "off"
      CUSTOM_LOGIN_INFO: ""
      CUSTOM_LOGO: ""
      MAX_UI_JOB_EVENTS: "4000"
      UI_LIVE_UPDATES_ENABLED: "true"
      AUTHENTICATION_BACKENDS:
        - awx.sso.backends.TACACSPlusBackend
        - awx.main.backends.AWXModelBackend
      SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL: "false"
      AUTH_LDAP_SERVER_URI: ""
      AUTH_LDAP_BIND_DN: ""
      AUTH_LDAP_BIND_PASSWORD: ""
      AUTH_LDAP_START_TLS: "false"
      AUTH_LDAP_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_USER_SEARCH:
        []
      AUTH_LDAP_USER_ATTR_MAP:
        {}
      AUTH_LDAP_GROUP_SEARCH:
        []
      AUTH_LDAP_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_TEAM_MAP:
        {}
      AUTH_LDAP_1_SERVER_URI: ""
      AUTH_LDAP_1_BIND_DN: ""
      AUTH_LDAP_1_BIND_PASSWORD: ""
      AUTH_LDAP_1_START_TLS: "false"
      AUTH_LDAP_1_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_1_USER_SEARCH:
        []
      AUTH_LDAP_1_USER_ATTR_MAP:
        {}
      AUTH_LDAP_1_GROUP_SEARCH:
        []
      AUTH_LDAP_1_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_1_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_1_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_1_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_1_TEAM_MAP:
        {}
      AUTH_LDAP_2_SERVER_URI: ""
      AUTH_LDAP_2_BIND_DN: ""
      AUTH_LDAP_2_BIND_PASSWORD: ""
      AUTH_LDAP_2_START_TLS: "false"
      AUTH_LDAP_2_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_2_USER_SEARCH:
        []
      AUTH_LDAP_2_USER_ATTR_MAP:
        {}
      AUTH_LDAP_2_GROUP_SEARCH:
        []
      AUTH_LDAP_2_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_2_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_2_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_2_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_2_TEAM_MAP:
        {}
      AUTH_LDAP_3_SERVER_URI: ""
      AUTH_LDAP_3_BIND_DN: ""
      AUTH_LDAP_3_BIND_PASSWORD: ""
      AUTH_LDAP_3_START_TLS: "false"
      AUTH_LDAP_3_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_3_USER_SEARCH:
        []
      AUTH_LDAP_3_USER_ATTR_MAP:
        {}
      AUTH_LDAP_3_GROUP_SEARCH:
        []
      AUTH_LDAP_3_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_3_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_3_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_3_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_3_TEAM_MAP:
        {}
      AUTH_LDAP_4_SERVER_URI: ""
      AUTH_LDAP_4_BIND_DN: ""
      AUTH_LDAP_4_BIND_PASSWORD: ""
      AUTH_LDAP_4_START_TLS: "false"
      AUTH_LDAP_4_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_4_USER_SEARCH:
        []
      AUTH_LDAP_4_USER_ATTR_MAP:
        {}
      AUTH_LDAP_4_GROUP_SEARCH:
        []
      AUTH_LDAP_4_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_4_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_4_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_4_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_4_TEAM_MAP:
        {}
      AUTH_LDAP_5_SERVER_URI: ""
      AUTH_LDAP_5_BIND_DN: ""
      AUTH_LDAP_5_BIND_PASSWORD: ""
      AUTH_LDAP_5_START_TLS: "false"
      AUTH_LDAP_5_CONNECTION_OPTIONS:
        OPT_REFERRALS: 0
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_5_USER_SEARCH:
        []
      AUTH_LDAP_5_USER_ATTR_MAP:
        {}
      AUTH_LDAP_5_GROUP_SEARCH:
        []
      AUTH_LDAP_5_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_5_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_5_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_5_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_5_TEAM_MAP:
        {}
      RADIUS_SERVER: ""
      RADIUS_PORT: "1812"
      RADIUS_SECRET: ""
      TACACSPLUS_HOST: ""
      TACACSPLUS_PORT: "49"
      TACACSPLUS_SECRET: ""
      TACACSPLUS_SESSION_TIMEOUT: "5"
      TACACSPLUS_AUTH_PROTOCOL: "ascii"
      TACACSPLUS_REM_ADDR: "false"
      SOCIAL_AUTH_GOOGLE_OAUTH2_CALLBACK_URL: "https://towerhost/sso/complete/google-oauth2/"
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ""
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ""
      SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS:
        []
      SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS:
        {}
      SOCIAL_AUTH_GITHUB_CALLBACK_URL: "https://towerhost/sso/complete/github/"
      SOCIAL_AUTH_GITHUB_KEY: ""
      SOCIAL_AUTH_GITHUB_SECRET: ""
      SOCIAL_AUTH_GITHUB_ORG_CALLBACK_URL: "https://towerhost/sso/complete/github-org/"
      SOCIAL_AUTH_GITHUB_ORG_KEY: ""
      SOCIAL_AUTH_GITHUB_ORG_SECRET: ""
      SOCIAL_AUTH_GITHUB_ORG_NAME: ""
      SOCIAL_AUTH_GITHUB_TEAM_CALLBACK_URL: "https://towerhost/sso/complete/github-team/"
      SOCIAL_AUTH_GITHUB_TEAM_KEY: ""
      SOCIAL_AUTH_GITHUB_TEAM_SECRET: ""
      SOCIAL_AUTH_GITHUB_TEAM_ID: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_CALLBACK_URL: "https://towerhost/sso/complete/github-enterprise/"
      SOCIAL_AUTH_GITHUB_ENTERPRISE_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_API_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_KEY: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_SECRET: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_CALLBACK_URL: "https://towerhost/sso/complete/github-enterprise-org/"
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_API_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_KEY: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_SECRET: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_ORG_NAME: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_CALLBACK_URL: "https://towerhost/sso/complete/github-enterprise-team/"
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_API_URL: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_KEY: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_SECRET: ""
      SOCIAL_AUTH_GITHUB_ENTERPRISE_TEAM_ID: ""
      SOCIAL_AUTH_AZUREAD_OAUTH2_CALLBACK_URL: "https://towerhost/sso/complete/azuread-oauth2/"
      SOCIAL_AUTH_AZUREAD_OAUTH2_KEY: ""
      SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET: ""
      SOCIAL_AUTH_OIDC_SECRET: ""
      SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: ""
      SOCIAL_AUTH_OIDC_VERIFY_SSL: "true"
      SAML_AUTO_CREATE_OBJECTS: "true"
      SOCIAL_AUTH_SAML_CALLBACK_URL: "https://towerhost/sso/complete/saml/"
      SOCIAL_AUTH_SAML_METADATA_URL: "https://towerhost/sso/metadata/saml/"
      SOCIAL_AUTH_SAML_SP_ENTITY_ID: ""
      SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: ""
      SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: ""
      SOCIAL_AUTH_SAML_ORG_INFO:
        {}
      SOCIAL_AUTH_SAML_TECHNICAL_CONTACT:
        {}
      SOCIAL_AUTH_SAML_SUPPORT_CONTACT:
        {}
      SOCIAL_AUTH_SAML_ENABLED_IDPS:
        {}
      SOCIAL_AUTH_SAML_SECURITY_CONFIG:
        requestedAuthnContext: false
      SOCIAL_AUTH_SAML_ORGANIZATION_ATTR:
        {}
      SOCIAL_AUTH_SAML_TEAM_ATTR:
        {}
      SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR:
        {}
      LOCAL_PASSWORD_MIN_LENGTH: "0"
      LOCAL_PASSWORD_MIN_DIGITS: "0"
      LOCAL_PASSWORD_MIN_UPPER: "0"
      LOCAL_PASSWORD_MIN_SPECIAL: "0"
      NAMED_URL_FORMATS:
        execution_environments: <name>
        organizations: <name>
        teams: <name>++<organization.name>
        credential_types: <name>+<kind>
        credentials: <name>++<credential_type.name>+<credential_type.kind>++<organization.name>
        notification_templates: <name>++<organization.name>
        job_templates: <name>++<organization.name>
        projects: <name>++<organization.name>
        inventories: <name>++<organization.name>
        hosts: <name>++<inventory.name>++<organization.name>
        groups: <name>++<inventory.name>++<organization.name>
        inventory_sources: <name>++<inventory.name>++<organization.name>
        instance_groups: <name>
        workflow_job_templates: <name>++<organization.name>
        workflow_job_template_nodes: <identifier>++<workflow_job_template.name>++<organization.name>
        labels: <name>++<organization.name>
        applications: <name>++<organization.name>
        users: <username>
        instances: <hostname>
      NAMED_URL_GRAPH_NODES:
        execution_environments:
          fields:
          - name
          adj_list: []
        organizations:
          fields:
          - name
          adj_list: []
        teams:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        credential_types:
          fields:
          - name
          - kind
          adj_list: []
        credentials:
          fields:
          - name
          adj_list:
          - - credential_type
            - credential_types
          - - organization
            - organizations
        notification_templates:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        job_templates:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        projects:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        inventories:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        hosts:
          fields:
          - name
          adj_list:
          - - inventory
            - inventories
        groups:
          fields:
          - name
          adj_list:
          - - inventory
            - inventories
        inventory_sources:
          fields:
          - name
          adj_list:
          - - inventory
            - inventories
        instance_groups:
          fields:
          - name
          adj_list: []
        workflow_job_templates:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        workflow_job_template_nodes:
          fields:
          - identifier
          adj_list:
          - - workflow_job_template
            - workflow_job_templates
        labels:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        applications:
          fields:
          - name
          adj_list:
          - - organization
            - organizations
        users:
          fields:
          - username
          adj_list: []
        instances:
          fields:
          - hostname
          adj_list: []
...
