---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: devspace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspace-operator
  namespace: devspace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspace-operator
  namespace: devspace
spec:
  channel: 'stable'
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---